name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: run MVN install
        run: mvn install # install maven

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install snyk -g # install snyk
      - run: snyk -v
      - run: snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets

        # Generate the HTML report
      - name: install snyk-to-html
        run: |
          # Install the Snyk JSON to HTML Mapper using npm
          npm install snyk-to-html -g
          # Convert JSON output from `snyk test --json` into a static HTML
          #snyk test --json | snyk-to-html -o result.html
          #mkdir downloads
          #cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

      - name: Snyk Open Source Scanning
        run: |
          snyk test --org=${{ secrets.SNYK_ORG }} --all-projects --sarif-file-output=snyk-oss.sarif
          # snyk test --org=${{ secrets.SNYK_ORG }} --all-projects --sarif-file-output=snyk-oss.sarif --severity-threshold=medium
          snyk monitor --org=${{ secrets.SNYK_ORG }} --all-projects
        continue-on-error: true
      - name: Upload results to GitHub Open Source Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-oss.sarif

      - name: Snyk Code Scanning
        run: |
          snyk code test --org=${{ secrets.SNYK_ORG }} --sarif-file-output=snyk-code.sarif
          # snyk code test --org=${{ secrets.SNYK_ORG }} --report --project-name='SAST'
        continue-on-error: true
      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

      # save the HTML in the artifact
      #- name: Use the Upload Artifact GitHub Action
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: results
      #    path: downloads
